### ISSUE TITLE
Sound when my turn.

### ISSUE THREAD

**Issue by Ud71p** [btouellette/concarneau#14]
Some players may take long time to make a move. Sometimes they're even away for a while.
I know there is currently an exclamation mark on tab title for that, but I often miss that. For instance if I have many tabs open, and I switch to another, I cannot see the title of the game tab anymore, only the icon. If I have really many tabs, then even the icon disappears.

It would really help if the game made a sound when it's my move again.

**Comment by btouellette** [comment]
Added option for this in 44364db2de23d02b072f07200f2013bd2e9f21bc. You can find a new setting to enable it in the settings menu.

**Comment by btouellette** [comment]
I don't have a good way to test whether this works from tabs in the background right this instant but let me know if it doesn't. From a cursory googling it looks like it should be okay if the tab has been focused to before but if not let me know and I'll see if I can find a good workaround.

**Comment by btouellette** [comment]
Working from background tab as of 6a8006146c2efcd8108cd54a686d2c0f7dfb27e5
