### ISSUE TITLE
Undo.

### ISSUE THREAD

**Issue by Ud71p** [btouellette/concarneau#19]
Sometimes I or my opponent forget to place a figure on a tile and we wish we could undo to do this. I don't know any rude opponents who would disallow this. Most are polite and allow it, because it is usually a 'mouse error' when one just clicks the green arrow twice due to habit, and forgets to place a figure. Such a mistake would normally never happen in real life game, so no opponent I think would object to undoing.

**Comment by btouellette** [comment]
This might get tricky since it'd have to handle out-of-turn gamestate updates from players (which may conflict with updates from the active player being submitted at the same time). Not sure the ROI is there to handle this properly.
