### ISSUE TITLE
Hide left pane.

### ISSUE THREAD

**Issue by Ud71p** [btouellette/concarneau#22]
The left pane (with game list) is very annoying during the game. It takes a large portion of the screen. And the screen estate is very precious. Once the game is started, I never need to use it for anything. The only useful thing there is the number of tiles remaining. But taking around 1/4 of the screen just to show this number is suboptimal.

I know the left pane allows to switch between games and play several simultaneous games. For me this possibility is only theoretical, this never happened to me.

So it would be nice to be able to hide the left pane, to use entire screen for the current game. Then of course the number of remaining tiles could be shown together with status, e.g. where the players' resources and points are shown.

**Comment by btouellette** [comment]
I had some code in to collapse the menu on small screen sizes but I've added an additional option under settings to enable the collapse regardless of screen size (4725d374477e526add7e6ab5a3c789953d0ab077).
