### ISSUE TITLE
Enter in chat accepts the move.

### ISSUE THREAD

**Issue by Ud71p** [btouellette/concarneau#25]
When I place a tile in one of possible gray areas, and then write text in chat, pressing enter, then the move gets accepted, as if I pressed enter outside of chat.

The feature of pressing enter instead of clicking the green forward arrow is fantastic. It makes it much easier to play. But enter in chat should not activate this feature. Perhaps the chat keyboard events should have bubbling cancelled.

**Comment by btouellette** [comment]
Good catch, fixed in 751a0102a965d4f08e7c7be3cf6cb6b617138485, thanks
