### ISSUE TITLE
Couldn't finish move

### ISSUE THREAD

**Issue by eltoncezar** [btouellette/concarneau#30]
Hi, this is a strange behavior that I can't precisely reproduce, but happens sometimes:

![weird](https://user-images.githubusercontent.com/2071672/43078616-5d3f20f0-8e61-11e8-81c6-279d295172fc.png)

The only way is to play the tile on another place (undesirable) or start a new game (even worse).

**Comment by btouellette** [comment]
If you open that game in a new browser does it still show up that way? Or if you do a hard refresh with CTRL+F5?

**Comment by eltoncezar** [comment]
Yes, I've already tried that on the lastest version of Firefox, Chrome and Edge. Also Chrome on Android.
Obviously I don't know the inner workings, but it seems to me like a server side issue...

**Comment by btouellette** [comment]
I'm seeing some DB errors in my back end logs. Appears this may be related to a DB version upgrade that one of my providers pushed through on July 20th. Were you seeing this behavior before that?

**Comment by btouellette** [comment]
If it is related it is hopefully fixed in 315bd112c82c325f2e7f8e4deff6d85fb2327d14, let me know if you still see failures

**Comment by eltoncezar** [comment]
You're awesome man! Everything working smooth now.

> Were you seeing this behavior before that?

No, I first noticed it around this date, so it makes sense.
Many thanks for your work, now my work colleagues and I can resume our procrastination LOL
