### ISSUE TITLE
Make email notifications work

### ISSUE THREAD

**Issue by rtealwitter** [btouellette/concarneau#34]
I've clicked "E-mail notifications" on the settings page but I do not receive email notifications when it's my turn. (I tried creating a "local" account and an account linked to Google but the problem persists in both.)

Thank you for your help!
![Screen Shot 2020-07-28 at 1 56 59 PM](https://user-images.githubusercontent.com/7432782/88714562-38a4e500-d0da-11ea-885f-beec58672a48.png)

**Comment by btouellette** [comment]
Looks like Google revoked the refresh token the app was using for OAuth. I've generated a new one and it appears to be working. Going to leave this open for a few days to make sure it doesn't get revoked again. Thanks.

**Comment by rtealwitter** [comment]
Thanks so much! It's working so far :)
