### ISSUE TITLE
Twitter login showing Internal Server Error

### ISSUE THREAD

**Issue by uditrana** [btouellette/concarneau#41]
We were middle of a game and it was my turn, I went to login and I got this error. It seems to go through the twitter login redirect fine, but fails on the callback to the heroku site. 

![image](https://user-images.githubusercontent.com/9621154/112051215-e738e280-8b0e-11eb-8a58-00decc5cffcc.png)

Our game is stuck mid-progress!

**Comment by btouellette** [comment]
Appears to be specific to the Twitter OAuth flow and unrelated to any recent changes. I'm taking a look.

**Comment by btouellette** [comment]
Can you try now?

**Comment by uditrana** [comment]
I cleared caches on your app and twitter and then retried and it worked!
