### ISSUE TITLE
Instructions needed

### ISSUE THREAD

**Issue by Ecofoot** [btouellette/concarneau#43]
Needs instructions on how to operate controls in this online version. Cannot do anything in a solo game. What is program doing? Need to be able to adjust time for next solo player to make move.

**Comment by btouellette** [comment]
After you click a grey square to place a tile you can click the placed tile
again to rotate it. Clicking the green check mark in the upper right will
allow you to optionally place meeples on the new tile and then clicking the
green arrow in the upper right will submit the move. After the move is
processed the next player (just you again in a solo game) will start the
same process again with the next tile.

**Comment by btouellette** [comment]
Thanks for the kind words!
