### ISSUE TITLE
New game button gone.

### ISSUE THREAD

**Issue by Ud71p** [btouellette/concarneau#6]
There was a button next to 'GAMES' for creating a new game, but I cannot see it anymore.

**Comment by Ud71p** [comment]
For those addicts who need to play anyway, I found a workaround. Open your browser's javascript console and run:

$('.fa-plus-square-o').click()

And you can create a game! Thanks for this great game.

**Comment by Ud71p** [comment]
To elaborate, the button is still there in DOM, but for some reason of styling, it has a width of 0, so it's not visible.

**Comment by btouellette** [comment]
I'll take a look at this Friday or this weekend. Thanks for reporting it.
In the mean time it might be worth trying in another browser or with any
browser extensions disabled.

**Comment by btouellette** [comment]
Fixed: https://github.com/btouellette/concarneau/commit/e150d486adacb31b97ffaae20d09fbbe6a97cbe1
