### ISSUE TITLE
Precise rules for number of tiles?

### ISSUE THREAD

**Issue by Ud71p** [btouellette/concarneau#9]
Hi, and thanks for this great game.

I think I've noticed some change in rules? I think long time ago there was more tiles than now? I'm not sure.

But I am sure that the number of tiles is being limited, because in some games a rare tile might not come.

In case I'm right that there is some limiting, it would be great to write these rules down, perhaps on a Wiki?

Even better, allow choosing number of tiles when creating a game. This way one could play a quick game, but still with 2 extensions.

**Comment by btouellette** [comment]
No change to the rules or the tile sets. There's only one situation in which not every tile would be played in a game and it is when a tile is drawn which doesn't have a valid placement on the field. In that case it silently discards the tile and draws another one for the user which could be confusing. I'll see if I can add a message to the game chat when a tile is discarded that way at least it can be verified that every tile was drawn at some point.

**Comment by Ud71p** [comment]
OK, I found the source for tile distribution, it's in tile.js/tileSchema.statics.loadTilesBase. Here in fact RCr.png has count=4, which is correct, but when I play it only appears once. Maybe the bug is that it has startingTile: true, and instead there should be one with startingTile: true and 3 with startingTile: false?

**Comment by btouellette** [comment]
Tile schema was fine but there was a bug where rather than just loading one less of the startingTile into the set of tiles it was skipped entirely. Fixed in 05e18241f67de373287ccfeba8a6d7a9e35c812a (for any new game created going forward). Thanks for the catch.
